### ISSUE TITLE
[OneDrive] Add .md fallback logic

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-word2md#101]
Once `fstab` is set into the project, a request to `/index.html` would try to fetch `/index.docx` in the corresponding OneDrive repo. If the file does not exist, request just fails. 
For https://github.com/davidnuescheler/theblog/issues/1 and certainly for other cases, we would need to manage md files instead of docs files in certain cases (like importing legacy read-only content). 
The request processing should then try:
- `index.docx` in OneDrive
- if no docx file, try `index.md` in OneDrive
- if no md file, try `index.md` in the git repository
- (if no md file in git repo, try `index.html` in the git repository) - no required for now

I did not test with Google Drive but I assume the same might apply.

cc @tripodsan

**Comment by kptdobe** [comment]
The need for the project is the fallback to md in Git. 
But more generally (might be for later), I think onedrive / google support should follow the dispatch rules (first fstab rules - might be a onedrive AND a google account configured, then `.md` in Git content repo, then `.html` in Git content repo...). Also in the simulator which is another current limitation btw.

**Comment by kptdobe** [comment]
Also, I wonder how this will play with https://github.com/adobe/helix-dispatch/pull/140. We start having "dispatching" logic at 2 different places.

**Comment by tripodsan** [comment]
> The need for the project is the fallback to md in Git.

but this is already in place! if you request `/posts/foo.html`, and there is no  `/foo.docx`, it will try to load the `/foo.md`

**Comment by kptdobe** [comment]
But this does not work... 
https://theblog-davidnuescheler.hlx.page/posts/adobe-named-a-leader-in-forresters-latest-enterprise-marketing-software-suites-report.html works from onedrive.
https://theblog-davidnuescheler.hlx.page/README.html does not work while there is a readme in the project.
