### ISSUE TITLE
Implement capability to subscribe for changes below a onedrive folder

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-word2md#115]
note: this functionality might be implemented on 1 or 2 runtime actions, but this repository currently holds as incubator.
---

it should be possible to subscribe an Adobe IO Runtime action as _listener_ for changes below a certain one-drive folder (or at least drive root).

it must
- have an endpoint that receives the [graph webhooks](https://docs.microsoft.com/en-us/graph/webhooks)
- retrieves the list of modified files since the last notification [graph delta](see https://docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-1.0&tabs=http).
- invokes a _configured_ action with the changes of modified drive items.

it should
- offer a (secure) possibility to setup the notification and include a `clientState` for further validation.

notes:
-  it might be difficult to implement this based on a last modified timestamp due to the nature of the delta functionality of the graph api, so the action needs to 'remember' the last delta-token.
- the listener action could be configured through action-params, which would imply that each hook/listener pair needs to be deployed as separate actions.
- the listener action could also be configured though the `clientState` which is setup when registering the webhook (on the ms-graph side). the `clientState` could be a JWT.

/cc @dominique-pfister

**Comment by dominique-pfister** [comment]
verified the following: using the drive item from a shared link, it is possible to invoke the `delta` API, and iterate through all pages until a `@odata.deltaLink` is received.

Calling that `@odata.deltaLink` then returns an empty array. Adding some file in the shared location will generate an element in the array for every parent folder that was modified, as well as the file itself.

**Comment by tripodsan** [comment]
> Question: when the change tracker action has no remembered state, and it gets triggered by the webhook action for the first time, should it generate an iindex call for _every_ item in the collection (seems like overkill), or should it fetch the latest `delta` and remember that (this might oversee an initial change)?

the later. i.e. it should **not** reindex everything. This needs to be an explicit decision by a human.

**Comment by tripodsan** [comment]
done.
