### ISSUE TITLE
Need Grammatical Help in README.md file

### ISSUE THREAD

**Issue by VikasPandey121** [adobe/helix-word2md#49]
Need Grammatical Help in README.md file i.e., in line 42 there is spelling mistake of word committed (It is written as "Commited" with a single t)

**Comment by tripodsan** [comment]
what is this issue about? please describe what the problem is.

**Comment by VikasPandey121** [comment]
Here in README.md file I observed some grammatical and spelling mistakes what I have taken care of so that the documentation of this repository can become even more expressive.
