### ISSUE TITLE
v1.3.6 broken

### ISSUE THREAD

**Issue by rofe** [adobe/helix-word2md#74]
**Description**
word2md@1.3.6 turned out to be unusable.

**To Reproduce**
- open https://adobeioruntime.net/api/v1/web/helix/helix-services-private/word2md@1.3.6/_status_check/healthcheck.json in your browser
- observe error message:
```json
{
  "code": "KUBvRArgEC9vCMMacMtwoYi2CF4UJyKP",
  "error": "There was an error processing your request."
}
```
- run `wsk activation get 1c7669fe74d54289b669fe74d59289c7`
- observe error message:
 "error": "Initialization has failed due to: Error: Unable to expose method \"then\"\n    at Object.plumbing.exposePromiseMethod (/nodejsAction/XXniogep/main.js:54915:19)\n    at ./node_modules/request-promise-core/configure/request2.js.module.exports (/nodejsAction/XXniogep/main.js:54672:83)\n    at Object.<anonymous> (/nodejsAction/XXniogep/main.js:54969:1)\n    at Object../node_modules/request-promise-native/lib/rp.js (/nodejsAction/XXniogep/main.js:54982:30)\n    at __webpack_require__ (/nodejsAction/XXniogep/main.js:30:30)\n    at Object../src/OneDrive.js (/nodejsAction/XXniogep/main.js:74823:12)\n    at __webpack_require__ (/nodejsAction/XXniogep/main.js:30:30)\n    at Object../src/index.js (/nodejsAction/XXniogep/main.js:75852:18)\n    at __webpack_require__ (/nodejsAction/XXniogep/main.js:30:30)\n    at /nodejsAction/XXniogep/main.js:94:18"

**Expected behavior**
No error in activation

**Version:**
1.3.6

**Additional context**
Production links for this action have been reset to 1.3.5 in order to restore the service.

**Comment by tripodsan** [comment]
fixed.
